### ISSUE TITLE
Demo files do not include the MIT license.

### ISSUE THREAD

**Issue by mdell-seradex** [GustavBrock/VBA.Cryptography#1]
Shouldn't the demo files include the MIT license in them?

**Comment by GustavBrock** [comment]
I guess so, but never thought of that. Thanks!

**Comment by mdell-seradex** [comment]
I did not create a pull request for this.
I am leaving this to you to address. 😄

**Comment by GustavBrock** [comment]
License information is now included in the demo applications.
